services:
  gitea-a:
    image: docker.gitea.com/gitea:latest
    container_name: gitea-a
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # You may need to adapt this for your specific docker environment
      - GITEA__webhook__ALLOWED_HOST_LIST=gitea-auto-mirror
      - GITEA__migrations__ALLOW_LOCALNETWORKS=true
      - GITEA__migrations__ALLOWED_DOMAINS=gitea-b:3000
      - GITEA__repository__ENABLE_PUSH_CREATE_ORG=true
      - GITEA__repository__ENABLE_PUSH_CREATE_USER=true
    restart: always
    volumes:
      - ./data/gitea-a/:/data/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
  gitea-b:
    image: docker.gitea.com/gitea:latest
    container_name: gitea-b
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__repository__ENABLE_PUSH_CREATE_ORG=true
      - GITEA__repository__ENABLE_PUSH_CREATE_USER=true
    restart: always
    volumes:
      - ./data/gitea-b/:/data/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8081:3000"
